---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: control-plane
  namespace: flux-system
spec:
  decryption:
    provider: sops
  interval: 5m
  path: ./clusters/prd/control-plane
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
