---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: control-plane
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  decryption:
    provider: sops
  dependsOn:
  - name: flux-system
  interval: 5m
  path: ./clusters/prd/control-plane
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
