---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: customers
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  decryption:
    provider: sops
  dependsOn:
  - name: control-plane
  interval: 5m
  path: ./clusters/prd/customers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
